version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: coachlibre
      POSTGRES_USER: coachlibre
      POSTGRES_PASSWORD: coachlibre123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coachlibre-network

  # Base de données vectorielle Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - coachlibre-network

  # API FastAPI
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://coachlibre:coachlibre123@postgres:5432/coachlibre
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - qdrant
    networks:
      - coachlibre-network
    volumes:
      - ./apps/api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Astro
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - coachlibre-network
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules

  # Redis pour le cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - coachlibre-network

  # Monitoring Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - coachlibre-network

  # Monitoring Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - coachlibre-network

  # n8n pour les workflows
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=coachlibre
      - DB_POSTGRESDB_USER=coachlibre
      - DB_POSTGRESDB_PASSWORD=coachlibre123
    depends_on:
      - postgres
    networks:
      - coachlibre-network

  # Flowise pour l'IA conversationnelle
  flowise:
    image: flowiseai/flowise:latest
    ports:
      - "3002:3000"
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=coachlibre
      - DATABASE_USER=coachlibre
      - DATABASE_PASSWORD=coachlibre123
    depends_on:
      - postgres
    networks:
      - coachlibre-network

volumes:
  postgres_data:
  qdrant_data:
  prometheus_data:
  grafana_data:

networks:
  coachlibre-network:
    driver: bridge 