apiVersion: apps/v1
kind: Deployment
metadata:
  name: coachlibre-frontend
  namespace: coachlibre
  labels:
    app: coachlibre-frontend
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coachlibre-frontend
  template:
    metadata:
      labels:
        app: coachlibre-frontend
        version: v1.0.0
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: coachlibre-frontend-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coachlibre-frontend-html
  namespace: coachlibre
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CoachLibre - Déployé sur K3s</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .container {
                background: white;
                padding: 3rem;
                border-radius: 20px;
                box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                text-align: center;
                max-width: 600px;
                margin: 2rem;
            }
            h1 {
                color: #333;
                margin-bottom: 1rem;
                font-size: 2.5rem;
            }
            .status {
                background: #4CAF50;
                color: white;
                padding: 1rem 2rem;
                border-radius: 50px;
                font-size: 1.2rem;
                margin: 2rem 0;
                display: inline-block;
            }
            .info {
                background: #f8f9fa;
                padding: 1.5rem;
                border-radius: 10px;
                margin: 1rem 0;
                text-align: left;
            }
            .timestamp {
                color: #666;
                font-size: 0.9rem;
                margin-top: 2rem;
            }
            .features {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 1rem;
                margin: 2rem 0;
            }
            .feature {
                background: #e3f2fd;
                padding: 1rem;
                border-radius: 10px;
                border-left: 4px solid #2196F3;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 CoachLibre</h1>
            <div class="status">✅ Déploiement Réussi sur K3s</div>
            
            <div class="info">
                <h3>📊 Informations de Déploiement</h3>
                <p><strong>Cluster:</strong> K3s Local</p>
                <p><strong>Namespace:</strong> coachlibre</p>
                <p><strong>Service:</strong> coachlibre-frontend-service</p>
                <p><strong>Ingress:</strong> coachlibre.local</p>
                <p><strong>Déployé le:</strong> <span id="timestamp"></span></p>
            </div>

            <div class="features">
                <div class="feature">
                    <h4>🔧 Infrastructure</h4>
                    <p>Kubernetes K3s avec ArgoCD</p>
                </div>
                <div class="feature">
                    <h4>🌐 Frontend</h4>
                    <p>Astro + React + TailwindCSS</p>
                </div>
                <div class="feature">
                    <h4>🤖 IA</h4>
                    <p>Multi-Agent System</p>
                </div>
                <div class="feature">
                    <h4>📱 Responsive</h4>
                    <p>Design moderne et adaptatif</p>
                </div>
            </div>
        </div>

        <script>
            document.getElementById('timestamp').textContent = new Date().toLocaleString('fr-FR');
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: coachlibre-frontend-service
  namespace: coachlibre
  labels:
    app: coachlibre-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: coachlibre-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coachlibre-frontend-ingress
  namespace: coachlibre
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: coachlibre.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coachlibre-frontend-service
            port:
              number: 80
